# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 700ce178792fc4983cdf9db35182f87f86c1e76c7bc64f9e3bcbd2aefb95da476a8ca95e6778ae21c1c8eb4c80c2fff9c8f5baa53ca0137720d0e633651c281c

test:
  secret_key_base: f9e0640f1afc20dbd4f55ed49aa3f35f211f5c3be93e715e38ec7170b0df905292abd7b25cf13466d3971b6d4c31113463479ecd8d4bb945409be8e6fdd32979

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
